sudo: false

language: python

python:
 - "3.4"
 - "3.5"
 - "3.6"

addons:
  apt:
    packages:
      - libgdal1h
      - gdal-bin
      - libgdal-dev

install:
 - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal<1.11'

 - pip install codecov
 - pip install -r requirements.txt
 - pip install -r requirements-test.txt

script:
 - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
 - tar xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
 - export PATH=`pwd`/phantomjs-2.1.1-linux-x86_64/bin:$PATH
 - coverage run --include="./*" --omit="*/tests/*","*/tests.py" manage.py test -v2

env:
  - SELENIUM_BROWSER=PhantomJS

after_success:
 - codecov
