matrix:
  include:

    - name: "Python 3.6 unit tests (with coverage)"
      language: python
      python: 3.6
      addons:
        postgresql: "9.5"
        apt:
          packages:
            - libgdal1h
            - gdal-bin
            - libgdal-dev
            - python3-psycopg2
            - postgresql-9.5-postgis-2.3
      install:
       - pip install codecov coverage
       - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal<1.11'
       - pip install psycopg2==2.7.4
       - pip install -r requirements.txt
       - pip install -r requirements-dev.txt
      before_script:
       - psql -U postgres -c "create extension postgis"
       - cp enhydris_project/settings/travis.py enhydris_project/settings/local.py
      script:
       - coverage run --include="./*" --omit="*/tests/*","*/tests.py","*/migrations/*","./enhydris_project/*" manage.py test -v2
      after_success:
       - codecov

    - name: "Python 3.5 unit tests"
      language: python
      python: 3.5
      addons:
        postgresql: "9.5"
        apt:
          packages:
            - libgdal1h
            - gdal-bin
            - libgdal-dev
            - python3-psycopg2
            - postgresql-9.5-postgis-2.3
      install:
       - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal<1.11'
       - pip install psycopg2==2.7.4
       - pip install -r requirements.txt
       - pip install -r requirements-dev.txt
      before_script:
       - psql -U postgres -c "create extension postgis"
       - cp enhydris_project/settings/travis.py enhydris_project/settings/local.py
      script:
       - ./manage.py test -v2

    - name: "Python linting (black, isort, flake8)"
      language: python
      python: 3.6
      install:
       - pip install isort flake8 black
      script:
       - black --check .
       - flake8 --max-line-length=88 .
       - isort --recursive --check-only --diff .

    - name: "JavaScript lint, unit tests and coverage"
      language: node_js
      node_js: lts/*
      install:
       - cd frontend
       - yarn install
      script:
       - yarn lint
       - yarn run jest
      after_success:
       - yarn add codecov
       - codecov
