language: python

python:
 - "3.3"
 - "3.4"
 - "3.5"

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev

install:
 # Work around https://github.com/macropin/django-registration/issues/103,
 # which to date has been fixed but not released.
 - pip install 'django-registration-redux<2'

 - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal<1.11'

 - pip install codecov

script:
 - coverage run setup.py test

after_success:
 - codecov
